[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "msessionexplorer"
version = "0.1.0"
description = "A Python package for managing session data with tables and metadata"
readme = "README.md"
requires-python = ">=3.6"
authors = [
    {name = "Duo Xu"}
]
dependencies = [
    "numpy",
    "pandas",
    "dill",
    "ipython",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
] 